# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app mc
#   namespace: flux-system
# spec:
#   targetNamespace: games
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#   path: ./kubernetes/apps/games/minecraft/atm8/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 50Gi
#       VOLSYNC_SOURCE_PVC: atm8-data
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app atm9-reloaded
#   namespace: flux-system
# spec:
#   targetNamespace: games
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#   path: ./kubernetes/apps/games/minecraft/atm9/app
#   components:
#     - ../../../../../components/volsync
#     # - ../../../../../components/gatus/external
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 100Gi
#       GATUS_SUBDOMAIN: mc
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app atm9-skyblock
  namespace: flux-system
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/games/minecraft/atm9-skyblock/app
  components:
    - ../../../../../components/volsync
    # - ../../../../../components/gatus/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 100Gi
      GATUS_SUBDOMAIN: mc
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app fool2025
  namespace: flux-system
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/games/minecraft/fool2025/app
  components:
    - ../../../../../components/volsync
    # - ../../../../../components/gatus/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 25Gi
      VOLSYNC_CLAIM: fool2025-data
