---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age13c7s5pmg2uusg7v3m4undk3dpcsgpgsd4cusk4qav3tgxz3kkvzqw4stcz"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age13c7s5pmg2uusg7v3m4undk3dpcsgpgsd4cusk4qav3tgxz3kkvzqw4stcz"
stores:
  yaml:
    indent: 2
