apiVersion: v1
kind: Pod
metadata:
  name: util
  namespace: games
spec:
  containers:
    - name: util
      image: ubuntu:latest
      resources:
        requests:
          memory: 128Mi
          cpu: 500m
        limits:
          memory: 512Mi
      volumeMounts:
        - name: config
          mountPath: /config
        - name: config-stuff
          mountPath: /config-stuff
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: atm9-data
    - name: config-stuff
      nfs:
        server: 10.1.0.3
        path: /mnt/Data/vault
