# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:tABZ0KiNlqBRaCrqs/lE+CExKQFsyypME7Xnh1ZE9IY=,iv:vJQbNaP0qkQtFgH1hq9CNHFEHa9mFhRY26tb0UPV0kk=,tag:y7xoeLEjhnc6+/MPZHGrvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13c7s5pmg2uusg7v3m4undk3dpcsgpgsd4cusk4qav3tgxz3kkvzqw4stcz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocmV6ZUkxTlMzT1F1dERj
        QVUxS1VSbWc1NmJWZ2VNZUhqUGtyaWo2bTNvCk9XM0ZyWjl6cXlXOVU1RHhIWWUy
        V3RIaFJtU3doNXZMS0tJR0RQWGh1WTQKLS0tIE11dXR3alNDcHl4WXd6ZzA1dTlW
        YisycEJCSHBNa3FsQ0lObEsyWkVVb3MK1rqEJBvgQhIrz50kOrudaz/PKMy0zyHT
        jaRm2NmT0nRquVZlRmtX+IHQmv5YVH7HLtdRVe/QXAOdPZhjaXwXLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T01:00:46Z"
  mac: ENC[AES256_GCM,data:BkIGcn7dU8Z4gOL5qiP0tTpDhi+cIohzLcrkbbgckVpmJjE9vYjpSXMEEvPZWluQJQVa9e0cAAnxaWkicU+NDpHKPKR+htc7e6MSMB9ddsVCLKbZxXC6gBeVBCbvYpQ84dgYSxHyjiJE6nlDYvV22IJgdMSlPChKF876i+dX15E=,iv:wwL/3YrW5kFm2VoRVacj4wCgq3TI5+vbGosOPj0xhNk=,tag:qlh9GeV6LGVbLRQRIh3zVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
