---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        READARR__AUTH__APIKEY: "{{ .readarr_api_key }}"
        PUSHOVER_TOKEN: "{{ .readarr_pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        READARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: &dbUser "{{ .readarr_postgres_user }}"
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .readarr_postgres_password }}"
        READARR__POSTGRES__MAINDB: readarr_main
        READARR__POSTGRES__LOGDB: readarr_log
        READARR__POSTGRES__CACHEDB: readarr_cache
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: pushover
    - extract:
        key: cloudnative-pg
