---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-data
provisioner: nfs.csi.k8s.io
parameters:
  server: zodiark.parsec.sh
  share: /mnt/Data
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
provisioner: nfs.csi.k8s.io
parameters:
  server: zodiark.parsec.sh
  share: /mnt/Data/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
