---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../../components/common
resources:
  - ./namespace.yaml
  - ./paperless/ks.yaml
