---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actions-runner-secret
    template:
      engineVersion: v2
      data:
        github_app_id: '{{ .ACTIONS_RUNNER_CONTROLLER_GITHUB_APP_ID }}'
        github_app_installation_id: '{{ .ACTIONS_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}'
        github_app_private_key: '{{ .ACTIONS_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}'
  dataFrom:
    - extract:
        key: actions-runner-controller
