apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cqnC7Vy1bQKd,iv:lFFPYbTEpNwhxVh8s6eVcpuclZajkQQVuOhnX8bRG1A=,tag:XAx+nplJhMOXEjBfX6358Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13c7s5pmg2uusg7v3m4undk3dpcsgpgsd4cusk4qav3tgxz3kkvzqw4stcz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQkQxSlZHbFQ4dHlRYmtv
        cEdaa3ZBSUNxTGZ1Zk1wbDdrS1JpV0FwaFNzCm1SdUErcjhHVzRTWFR4cGo1VE1Y
        N2I5ZjlpMXV2VTgvL240MnV6WnNmdE0KLS0tIGVRN3hzTTlmN05XaWUwZ0d3R1Ra
        cm1aN21CZHNoRVdRb1pzdGg3UElDcmMKTAakBffkMyikmrk9vJEuFBIEbxPAv0/N
        pfDyIsVIpiJT6tMwLkbHQvgR+rqTZPuJgM8ccGNgsI0qqqnoxnRqIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T01:00:46Z"
  mac: ENC[AES256_GCM,data:ZJmOfxtnOTHptI1si7sl3iTzM08h7hTd12Dtkm94/sTl7Qjum+ladM39amtfnTQ+E5TTXnr1N2xpdBj4psZlLMCe2OQFoUz/QgvNGwzKXz8n9J9IH1TiQxeWKvcaEccJyu8Zb815wMRx4oxyN2xjxwMwC8BUVrIL3YefesmDg4E=,iv:BpYhFz6NO5YSi+LWptAs0p0eejLis9JpCJWmvjpVOpM=,tag:piP5ceCSlcBVZMgpgF1GmA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
