# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Po4kgqTybwuBACYmvi+5GpDwyfJCHzFYr+cy0jiRhLFTuDMpYf4ieg==,iv:P1OeYEMBA5U2qt9J95rafB+MByRp/sIH3adNKl03XuU=,tag:PO7taEV7wicoDyFH7GTkyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13c7s5pmg2uusg7v3m4undk3dpcsgpgsd4cusk4qav3tgxz3kkvzqw4stcz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVis5KzhMUVIraWVVYjRX
        blZpdVo3bkdpeEhJVlNkTkRGL01qK0JtbDA4CmFBb2RLemxqUGNiQjZLbW56TXhi
        R1kvYjNtSWxQMDJuSFpsQjROMzdOVzAKLS0tIFY3eGNDb2t2M0xnbm91Y0F0QUtY
        R0FZODlJV3dvWUt2ZXZEQmhKTjhpemMKrX4iAvXjHuJpIteR6nk7IL0gDTNemMTe
        9z7NOApE3d7uj8O691CcUSiD5NGO7scb3yRLgoXUEIm6lP5Hj5E7tA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T01:00:46Z"
  mac: ENC[AES256_GCM,data:AdvBIb5ivIPd2oTNtIAwL4yBhjjzd8nZdlD2cG7GIPTNai7pCR9zdO2yE/0grKWyHZnI3XniGec+nC5bMc3M5wM3Bzguu5UQrTpY1Bdhmq0QvbZMXt3KEsz+833Mb7S7wRUUqEDnZ6ONfejjjfrSbmGeDovUn3ubmQoz/ENbjU4=,iv:v6yVag/EZDJJoUOdoeljQxXBKoDJK92tNvZeDljX/0s=,tag:5DdfCy4hEJy2DE1LgVRvAQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
