---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atm9-reloaded
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.24.0
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    image:
      repository: itzg/minecraft-server
      tag: java17-graalvm
      pullPolicy: IfNotPresent
    nodeSelector:
      org.democratic-csi.topology/node: "hydaelyn"
    resources:
      requests:
        memory: 10Gi
        cpu: 4
      # limits:
      #  memory: 10Gi
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10

    minecraftServer:
      eula: true
      ops: "p4rsec"
      version: 1.20.1
      type: "AUTO_CURSEFORGE"
      forgeVersion: "47.4.0"
      spawnProtection: 0
      memory: 10G
      jvmOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      gameMode: survival
      maxTickTime: -1
      difficulty: normal
      pvp: true
      motd: "Welcome to All the Mods 9!"
      woldSaveName: atm9
      autoCurseForge:
        apiKey:
          existingSecret: atm9-secret
          secretKey: CF_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/6322046"
      serviceType: LoadBalancer
      servicePort: 25595
      loadBalancerIP: 10.1.10.103
      rcon:
        enabled: true
        port: 25575
      # extraPorts:
      #   - name: map
      #     containerPort: 8123
      #     protocol: TCP
      #     service:
      #       enabled: true
      #       type: ClusterIP
      #       port: 8123
      #     ingress:
      #       ingressClassName: external
      #       enabled: true
      #       annotations:
      #         external-dns.alpha.kubernetes.io/target: external.parsec.sh
      #         nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      #       hosts:
      #         - name: &host atm9-map.parsec.sh
      #           path: /
      #       tls:
      #         - hosts:
      #             - *host
    extraEnv:
      ALLOW_FLIGHT: true
      GUI: false
      STOP_SERVER_ANNOUNCE_DELAY: 60
    mcbackup:
      enabled: true
      initialDelay: 5m
      backupInterval: 4h
      pauseIfNoPlayers: true
      pruneBackupsDays: 1
      backupMethod: rclone
      rcloneRemote: zodiark
      rcloneDestDir: ./atm9
      rcloneConfig: |
        [zodiark]
        type = ftp
        host = 10.1.0.3
        user = anonymous
        pass = gIXs6-hO5MLIuYg0s3DvfL0P4_-ZbETioA
        port = 21
      resources:
        requests:
          memory: 500Mi
          cpu: 500m
        limits:
          memory: 2Gi
    persistence:
      dataDir:
        enabled: true
        existingClaim: atm9-reloaded-data
        readOnly: false
        globalMounts:
          - path: /data
