# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.1.0.117:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.1.0.117"
  - "k8s-api.parsec.sh"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "venat"
    ipAddress: "10.1.0.4"
    installDiskSelector:
      wwid: "naa.5002538f54711aa4"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/e770ae054f99369321899aef8b1fa5b71ef7075f24d3663da1a115eaac46e537
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e0:07:1b:64:10:d0"
          physical: true
        dhcp: false
        addresses:
          - "10.1.0.4/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.0.1"
        mtu: 1500
        vip:
          ip: "10.1.0.117"
        vlans:
          - &vlan10
            vlanId: 10
            dhcp: false
            mtu: 1500
      # - interface: br0
      #   dhcp: false
      #   addresses:
      #     - "10.1.0.4/24"
      #   bridge:
      #     stp:
      #       enabled: true
      #     interfaces: [bond0]
      #   routes:
      #     - network: "0.0.0.0/0"
      #       gateway: "10.1.0.1"
      #   vip:
      #     ip: "10.1.0.117"
      #   vlans:
      #     - &vlan10
      #       vlanId: 10
      #       dhcp: false
      #       mtu: 1500
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     primaryReselect: better
      #     updelay: 200
      #     downdelay: 200
      #     deviceSelectors:
      #       - hardwareAddr: "e0:07:1b:64:10:*"
      #         physical: true
      #   dhcp: false
      # - deviceSelector:
      #     hardwareAddr: "a0:36:9f:09:0b:3c"
      #     physical: true
      #   ignore: true
    patches:
      - "@./patches/venat/gpu-worker-patch.yaml"

  - hostname: "emet-selch"
    ipAddress: "10.1.0.5"
    installDiskSelector:
      size: "512110190592"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2d61dd07b20062062ea671b4d01873506103b67c0f7a4c3fb6cf4ee85585dcb8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "7c:69:f6:8f:bd:02"
          physical: true
        dhcp: false
        addresses:
          - "10.1.0.5/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.0.1"
        mtu: 1500
        vip:
          ip: "10.1.0.117"
        vlans:
        - *vlan10

  - hostname: "hythlodaeus"
    ipAddress: "10.1.0.6"
    installDiskSelector:
      wwid: "nvme.c0a9-323032304532413245324138-4354353030503253534438-00000001"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2d61dd07b20062062ea671b4d01873506103b67c0f7a4c3fb6cf4ee85585dcb8
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:b2:03:04:cd:31"
          physical: true
        dhcp: false
        addresses:
          - "10.1.0.6/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.0.1"
        mtu: 1500
        vip:
          ip: "10.1.0.117"
        vlans:
        - *vlan10
      # - interface: bond0
      #   bond:
      #     mode: 802.3ad
      #     miimon: 100
      #     xmitHashPolicy: layer3+4
      #     lacpRate: fast
      #     updelay: 200
      #     downdelay: 200
      #     deviceSelectors:
      #       - hardwareAddr: "54:b2:03:04:cd:*"
      #         physical: true
      #   dhcp: false
      #   routes:
      #   - network: "0.0.0.0/0"
      #     gateway: "10.1.0.1"
      #   addresses:
      #     - "10.1.0.6/24"
      #   vip:
      #     ip: "10.1.0.117"
      #   vlans:
      #   - *vlan10

  - hostname: "hydaelyn"
    ipAddress: "10.1.0.7"
    installDiskSelector:
      wwid: "eui.002538b531a470f9"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/9c1d1b442d73f96dcd04e81463eb20000ab014062d22e1b083e1773336bc1dd5
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:71:64:3f"
          physical: true
        dhcp: false
        addresses:
          - "10.1.0.7/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.0.1"
        mtu: 1500
        vlans:
        - *vlan10
      # - interface: bond0
      #   bond:
      #     mode: 802.3ad
      #     miimon: 100
      #     xmitHashPolicy: layer3+4
      #     lacpRate: fast
      #     updelay: 200
      #     downdelay: 200
      #     deviceSelectors:
      #       - hardwareAddr: "a0:ce:c8:31:92:3b"
      #       - hardwareAddr: "58:47:ca:71:64:3f"
      #   dhcp: false
      #   routes:
      #     - network: "0.0.0.0/0"
      #       gateway: "10.1.0.1"
      #   addresses:
      #     - "10.1.0.7/24"
      #   vlans:
      #     - *vlan10

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-features.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-talos-api.yaml"

