---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fool2025
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.24.0
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    image:
      repository: itzg/minecraft-server
      tag: java17-graalvm
      pullPolicy: IfNotPresent
    nodeSelector:
      org.democratic-csi.topology/node: "hydaelyn"
    resources:
      requests:
        memory: 6Gi
        cpu: 4
      # limits:
      #  memory: 10Gi
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10

    minecraftServer:
      eula: true
      ops: "p4rsec"
      version: 25w14craftmine
      type: "VANILLA"
      spawnProtection: 0
      memory: 10G
      jvmOpts: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      gameMode: survival
      maxTickTime: -1
      difficulty: normal
      pvp: true
      motd: "We're all mad here, Alice."
      woldSaveName: aprilfools2025
      serviceType: LoadBalancer
      servicePort: 25596
      loadBalancerIP: 10.1.10.104
    extraEnv:
      ALLOW_FLIGHT: true
      GUI: false
      STOP_SERVER_ANNOUNCE_DELAY: 60
    persistence:
      dataDir:
        enabled: true
        existingClaim: fool2025-data
        readOnly: false
        globalMounts:
          - path: /data
