---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nvidia-device-plugin
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/kube-system/nvidia/device-plugin/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: node-feature-discovery
