---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: homeassistant
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: hass.parsec.sh
          query-type: A
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
