---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    image:
      # https://github.com/backube/volsync/issues/828
      repository: &image ghcr.io/home-operations/volsync
      tag: &tag v0.12.0@sha256:95a572c6a9937ac8e7f1e7c82466e6ab4cf5914078ddbef27d11293e4659716f
    rclone:
      repository: *image
      tag: *tag
    restic:
      repository: *image
      tag: *tag
    metrics:
      disableAuth: true
